name: NuBeton_JobsReborn
main: net.livecar.NuttyWorks.nuBeton_JobsReborn.nuBetonJobsReborn
version: 1.6
description: Extends BetonQuest to interface with Jobs reborn
authors: [Nutty101]
depend: [Jobs,BetonQuest]
